import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import {ParticleLayerClient} from "components/ui/ParticlesBackground";
import Header from "../components/Header";
import Footer from "../components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],

})

export const metadata: Metadata = {
  title: "Jhack's Portfolio Website",
  description: "Generated by create next app",
  // icons:
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Header></Header>
        {/* Render only the Particles on Home Page */}
        <ParticleLayerClient></ParticleLayerClient>
        <main className="flex-auto flex-col min-h-[100vh] px-6 md:px-12 lg:px-20 py-8">
          {children}
        </main>

        <Footer></Footer>
      </body>
    </html>
  );
}
